name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: pain
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: fmt check
        run: nix build .#checks.fmt -L

      - name: clippy check
        run: nix build .#checks.clippy -L
        
      - name: nextest check
        run: nix build .#checks.nextest -L

      - name: doc tests
        run: nix build .#checks.doc -L

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: pain
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: fmt check
        run: nix build .#tricc -L